// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func MFASetup(qrCode string, secret string, mfaEnabled bool, errorMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>2FA Setup - SAML Proxy</title><script defer src=\"https://cdn.jsdelivr.net/npm/alpinejs@3.14.3/dist/cdn.min.js\" integrity=\"sha384-iZD2X8o1Zdq0HR5H/7oa8W30WS4No+zWCKUPD7fHRay9I1Gf+C4F8sVmw7zec1wW\" crossorigin=\"anonymous\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = authStyles().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = mfaStyles().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</head><body><div class=\"auth-container\"><h1>2FA Setup</h1><div id=\"mfa-setup-form\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = MFASetupForm(qrCode, secret, mfaEnabled, errorMsg).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><p class=\"link-text\"><a href=\"/admin/logs\">Back to Dashboard</a></p></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func MFASetupForm(qrCode string, secret string, mfaEnabled bool, errorMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"auth-form\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if errorMsg != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"error-msg\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(errorMsg)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/templates/mfa.templ`, Line: 31, Col: 36}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if mfaEnabled {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"success-msg\">2FA is currently enabled</div><p class=\"mfa-info\">To disable 2FA, enter a code from your authenticator app:</p><form x-data=\"{ loading: false }\" @submit.prevent=\"\n\t\t\t\t\tloading = true;\n\t\t\t\t\tfetch('/admin/2fa/disable', {\n\t\t\t\t\t\tmethod: 'POST',\n\t\t\t\t\t\tbody: new FormData($el)\n\t\t\t\t\t})\n\t\t\t\t\t.then(r => r.text())\n\t\t\t\t\t.then(html => {\n\t\t\t\t\t\tdocument.getElementById('mfa-setup-form').innerHTML = html;\n\t\t\t\t\t})\n\t\t\t\t\t.catch(() => { loading = false; })\n\t\t\t\t\"><div class=\"form-group\"><label for=\"code\">Verification Code</label> <input type=\"text\" id=\"code\" name=\"code\" placeholder=\"000000\" pattern=\"[0-9]{6}\" maxlength=\"6\" autocomplete=\"one-time-code\" inputmode=\"numeric\" required></div><button type=\"submit\" class=\"btn-submit btn-danger\" :disabled=\"loading\"><span x-show=\"!loading\">Disable 2FA</span> <span x-show=\"loading\">Disabling...</span></button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<p class=\"mfa-info\">Scan the QR code with your authenticator app (Google Authenticator, Authy, etc.):</p><div class=\"qr-container\"><img src=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("data:image/png;base64," + qrCode)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/templates/mfa.templ`, Line: 73, Col: 48}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" alt=\"2FA QR Code\" class=\"qr-code\"></div><div class=\"secret-display\"><label>Manual Entry Code:</label> <code class=\"secret-code\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(secret)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/templates/mfa.templ`, Line: 77, Col: 38}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</code></div><form x-data=\"{ loading: false }\" @submit.prevent=\"\n\t\t\t\t\tloading = true;\n\t\t\t\t\tfetch('/admin/2fa/enable', {\n\t\t\t\t\t\tmethod: 'POST',\n\t\t\t\t\t\tbody: new FormData($el)\n\t\t\t\t\t})\n\t\t\t\t\t.then(r => r.text())\n\t\t\t\t\t.then(html => {\n\t\t\t\t\t\tdocument.getElementById('mfa-setup-form').innerHTML = html;\n\t\t\t\t\t})\n\t\t\t\t\t.catch(() => { loading = false; })\n\t\t\t\t\"><input type=\"hidden\" name=\"secret\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(secret)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/templates/mfa.templ`, Line: 94, Col: 53}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\"><div class=\"form-group\"><label for=\"code\">Verification Code</label> <input type=\"text\" id=\"code\" name=\"code\" placeholder=\"000000\" pattern=\"[0-9]{6}\" maxlength=\"6\" autocomplete=\"one-time-code\" inputmode=\"numeric\" required></div><button type=\"submit\" class=\"btn-submit\" :disabled=\"loading\"><span x-show=\"!loading\">Enable 2FA</span> <span x-show=\"loading\">Verifying...</span></button></form>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func MFAVerify(errorMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Verify 2FA - SAML Proxy</title><script defer src=\"https://cdn.jsdelivr.net/npm/alpinejs@3.14.3/dist/cdn.min.js\" integrity=\"sha384-iZD2X8o1Zdq0HR5H/7oa8W30WS4No+zWCKUPD7fHRay9I1Gf+C4F8sVmw7zec1wW\" crossorigin=\"anonymous\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = authStyles().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = mfaStyles().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</head><body><div class=\"auth-container\"><h1>2FA Verification</h1><div id=\"mfa-verify-form\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = MFAVerifyForm(errorMsg).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func MFAVerifyForm(errorMsg string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var8 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var8 == nil {
			templ_7745c5c3_Var8 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<form class=\"auth-form\" x-data=\"{ loading: false }\" @submit.prevent=\"\n\t\t\tloading = true;\n\t\t\tfetch('/admin/2fa/verify', {\n\t\t\t\tmethod: 'POST',\n\t\t\t\tbody: new FormData($el)\n\t\t\t})\n\t\t\t.then(r => {\n\t\t\t\tif (r.headers.get('HX-Redirect')) {\n\t\t\t\t\twindow.location.href = r.headers.get('HX-Redirect');\n\t\t\t\t} else {\n\t\t\t\t\treturn r.text();\n\t\t\t\t}\n\t\t\t})\n\t\t\t.then(html => {\n\t\t\t\tif (html) {\n\t\t\t\t\tdocument.getElementById('mfa-verify-form').innerHTML = html;\n\t\t\t\t}\n\t\t\t})\n\t\t\t.catch(() => { loading = false; })\n\t\t\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if errorMsg != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<div class=\"error-msg\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(errorMsg)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `frontend/templates/mfa.templ`, Line: 166, Col: 36}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "<p class=\"mfa-info\">Enter the 6-digit code from your authenticator app:</p><div class=\"form-group\"><label for=\"code\">Verification Code</label> <input type=\"text\" id=\"code\" name=\"code\" placeholder=\"000000\" pattern=\"[0-9]{6}\" maxlength=\"6\" autocomplete=\"one-time-code\" inputmode=\"numeric\" autofocus required></div><button type=\"submit\" class=\"btn-submit\" :disabled=\"loading\"><span x-show=\"!loading\">Verify</span> <span x-show=\"loading\">Verifying...</span></button><p class=\"link-text\"><a href=\"/admin/login\">Cancel and return to login</a></p></form>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func mfaStyles() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var10 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var10 == nil {
			templ_7745c5c3_Var10 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "<style>\n\t\t.mfa-info {\n\t\t\tcolor: #888;\n\t\t\tfont-size: 0.9rem;\n\t\t\tmargin-bottom: 1.5rem;\n\t\t\ttext-align: center;\n\t\t}\n\t\t.qr-container {\n\t\t\tdisplay: flex;\n\t\t\tjustify-content: center;\n\t\t\tmargin: 1.5rem 0;\n\t\t}\n\t\t.qr-code {\n\t\t\tbackground: white;\n\t\t\tpadding: 1rem;\n\t\t\tborder-radius: 8px;\n\t\t}\n\t\t.secret-display {\n\t\t\tbackground: rgba(255,255,255,0.05);\n\t\t\tborder-radius: 8px;\n\t\t\tpadding: 1rem;\n\t\t\tmargin-bottom: 1.5rem;\n\t\t\ttext-align: center;\n\t\t}\n\t\t.secret-display label {\n\t\t\tdisplay: block;\n\t\t\tmargin-bottom: 0.5rem;\n\t\t\tcolor: #666;\n\t\t\tfont-size: 0.8rem;\n\t\t}\n\t\t.secret-code {\n\t\t\tfont-family: 'JetBrains Mono', monospace;\n\t\t\tfont-size: 0.9rem;\n\t\t\tcolor: #e94560;\n\t\t\tword-break: break-all;\n\t\t\tuser-select: all;\n\t\t}\n\t\t.success-msg {\n\t\t\tbackground: rgba(46, 204, 113, 0.15);\n\t\t\tborder: 1px solid #2ecc71;\n\t\t\tborder-radius: 8px;\n\t\t\tpadding: 0.75rem 1rem;\n\t\t\tmargin-bottom: 1.5rem;\n\t\t\tcolor: #2ecc71;\n\t\t\tfont-size: 0.9rem;\n\t\t\ttext-align: center;\n\t\t}\n\t\t.btn-danger {\n\t\t\tbackground: linear-gradient(135deg, #c0392b, #e74c3c);\n\t\t}\n\t\t.btn-danger:hover:not(:disabled) {\n\t\t\tbackground: linear-gradient(135deg, #a93226, #c0392b);\n\t\t}\n\t\tinput[type=\"text\"]#code {\n\t\t\twidth: 100%;\n\t\t\tpadding: 1rem;\n\t\t\tborder: 2px solid rgba(233, 69, 96, 0.3);\n\t\t\tborder-radius: 8px;\n\t\t\tbackground: rgba(255,255,255,0.05);\n\t\t\tcolor: #fff;\n\t\t\tfont-size: 1.5rem;\n\t\t\tfont-family: 'JetBrains Mono', monospace;\n\t\t\ttext-align: center;\n\t\t\tletter-spacing: 0.5em;\n\t\t\toutline: none;\n\t\t\ttransition: border-color 0.2s;\n\t\t}\n\t\tinput[type=\"text\"]#code:focus {\n\t\t\tborder-color: #e94560;\n\t\t}\n\t</style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
